### ISSUE TITLE
Cannot find module 'api/fixtures/user.json'

### ISSUE THREAD

**Issue by usenkanov** [bredikhin/barrels#19]
I have fixtures in /test/fixtures folder, everything works fine. I'm running fixtures like this: 
var barrels = new Barrels();

I decided to populate another set of fixtures (for local dev environment) which are located in: /api/fixtures
which means I have to use barrels like this: 
var barrels = new Barrels('./api/fixtures/');

however, when I do this I get this error: 

error: Sent 500 ("Server Error") response
error: Error: Cannot find module 'api/fixtures/user.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new Barrels (/Users/usenkanov/projects/xxx/node_modules/barrels/index.js:42:30)
    at module.exports.populate (/Users/usenkanov/projects/xxx/api/controllers/DbController.js:10:23)
    at routeTargetFnWrapper (/Users/usenkanov/projects/xxx/node_modules/sails/lib/router/bind.js:178:5)
    at callbacks (/Users/usenkanov/projects/xxx/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/usenkanov/projects/xxx/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/usenkanov/projects/xxx/node_modules/sails/node_modules/express/lib/router/index.js:145:5) { [Error: Cannot find module 'api/fixtures/user.json'] code: 'MODULE_NOT_FOUND' }

**Comment by bredikhin** [comment]
Actually, should work if you're starting tests from the project root folder. Could you try `var barrels = new Barrels(process.cwd() + '/api/fixtures/');`?

**Comment by usenkanov** [comment]
Aw! I was running from within IDE. You are right. Solution works. Thanks.
