### ISSUE TITLE
association model name constrainte

### ISSUE THREAD

**Issue by devitito** [bredikhin/barrels#22]
Hi,
I have 2 models (let say User and Pet). Models are defined in User.js and Pet.js (in singular). 
I have an association many-to-one. One user can have many pets but a pet can have only one user.

In User.js, the association is defined like that:
pets: {
      notNull: true,
      required: true,
      collection: 'Pet',
      via: 'pet_id'
    },

The fixture for user is:
[
  {
    "id": "1",
    "pets": [1,2]
  }
]

I populate the db this way:
  barrels.populate(['pet'], function(err) {
        if (err) return reject(err);
        barrels.populate(['user'], function(err) {
          if (err) reject(err);
          else resolve();
        }, false);
      }, false);

The association fails (sails don't lift and an error is thrown during before all hook). The association for pets cannot be done because 'pets.json' doesn't exist. The fixture filename is 'pet.json' and it is pet.json because the filename of my model is Pet.js. 

I could rename the model filename, but it would affect all the blueprints handled by sails... 

Would it be possible to mention in each fixture file to which model it is binding, without using the filename all the time?

**Comment by bredikhin** [comment]
Well, if Sails can't get lifted, as you're saying, then maybe it's not a Barrels' problem: Barrels should only be used after the app is already lifted (see an example [here](https://github.com/bredikhin/sailsjs-mocha-testing-barrels-fixtures-example)).

**Comment by devitito** [comment]
My mistake. Sails lift. Here is the error stack:
Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined' at line 1
    at Query.Sequence._packetToError (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
    at Query.ErrorPacket (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
    at Parser.write (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:75:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
    --------------------
    at Protocol._enqueue (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:110:48)
    at PoolConnection.Connection.query (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:166:25)
    at __FIND__ (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/adapter.js:836:20)
    at Object.module.exports.adapter.find (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/adapter.js:803:9)
    at Array.__DESTROY__.async.auto.findRecords [as 0] (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/adapter.js:1055:21)
    at /home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/async/lib/async.js:487:38
    at Array.forEach (native)
    at _each (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/async/lib/async.js:46:24)
    at Object.async.auto (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/async/lib/async.js:458:9)
    at __DESTROY__ (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/adapter.js:1052:15)
    at afterwards (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/connections/spawn.js:86:5)
    at /home/devitito/projects/mindmeteo/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping._callback (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:81:7)
    at Ping.Sequence.end (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Ping.Sequence.OkPacket (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:87:8)
    at Protocol._parsePacket (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:213:24)
    at Parser.write (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/home/devitito/projects/mindmeteo/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:75:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

Details:  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'undefined' at line 1

  1) "before all" hook


  0 passing (1s)
  1 failing

  1)  "before all" hook:

**Comment by bredikhin** [comment]
I don't see anything related to fixtures in the stack. A couple of suggestions, though:
1. Are you using a separate DB to run tests? 'Cause there's a chance you're having some troubles while trying to clean up the existing tables, may be because of MySQL constraints and whatnot.
2. Try to log the query and find out which parameter is undefined.
