### ISSUE TITLE
sails is not defined

### ISSUE THREAD

**Issue by gutenye** [bredikhin/barrels#48]
Run with

```
#!/usr/bin/env node

var Barrels = require("barrels")
var barrels = new Barrels()
barrels.populate(err => {
  console.log(err)
})
```

Got this error

```
/Users/guten/a/sails/hello/node_modules/barrels/index.js:132
    var Model = sails.models[modelName];
                            ^

TypeError: Cannot read property 'users' of undefined
    at /Users/guten/a/sails/hello/node_modules/barrels/index.js:132:29
    at /Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:209:22)
    at Barrels.populate (/Users/guten/a/sails/hello/node_modules/barrels/index.js:131:51)
    at Object.<anonymous> (/Users/guten/a/sails/hello/fixtures.js:19:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by bredikhin** [comment]
Which version of Sails?

**Comment by gutenye** [comment]
0.12.3

Where to put the first part the of code?

**Comment by gutenye** [comment]
Actually, the error is 

```
/Users/guten/a/sails/hello/node_modules/barrels/index.js:131
    var Model = sails.models[modelName];
                ^

ReferenceError: sails is not defined
    at /Users/guten/a/sails/hello/node_modules/barrels/index.js:131:17
    at /Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/guten/a/sails/hello/node_modules/barrels/node_modules/async/lib/async.js:209:22)
    at Barrels.populate (/Users/guten/a/sails/hello/node_modules/barrels/index.js:130:51)
    at Object.<anonymous> (/Users/guten/a/sails/hello/fixtures.js:9:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

I did not find barrels require("sails") in source files.

**Comment by bredikhin** [comment]
To be honest, it was never tested with `0.12.x`. For previous versions, it was operating under assumption that `sails` variable is globalized.

**Comment by gutenye** [comment]
I found a solution, not the best but works

```
var sails = require("sails")
var rc = require("rc")
var Barrels = require("barrels")

sails.lift(rc("sails"), err => {
  new Barrels().populate(err => {
    console.log(err)
  })
})
```
